### ISSUE TITLE
python-pymod2pkg is missing runtime dep on python-pbr

### ISSUE THREAD

**Issue by tbreeds** [softwarefactory-project/rdopkg#130]
On my F26 Laptop:

```
[tony@thor ~]$ dnf install rdopkg
<SNIP>
[tony@thor ~]$ rdopkg info subunit
Traceback (most recent call last):
  File "/usr/bin/rdopkg", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3037, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3021, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3050, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 969, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 855, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pbr>=1.6' distribution was not found and is required by pymod2pkg
[tony@thor ~]$ dnf install python-pbr
<SNIP>
Complete!
[tony@thor ~]$ rdopkg info subunit
1 packages found:
<SNIP>
```

**Comment by yac** [comment]
Interesting, `pbr` requirement was only recently added to master, it wasn't released and latest packaged version `0.43` doesn't need pbr.

So it looks like some local installation is interfering, possibly git master?

Anyway, the Requires are missing indeed so here is a fix for next release:
https://softwarefactory-project.io/r/#/c/8931/

**Comment by tbreeds** [comment]
Thanks for updating the spec.  I don't have an install from git master.  My bash history shows:

```
dnf copr enable jruzicka/rdopkg
dnf install rdopkg
rdopkg info subunit
dnf install python-pbr
rdopkg info subunit
```

Oh I'm mistaken!  The trace above says that pymod2pkg needs pbr not rdopkg.  Checking pymod2pkg I see:

```
[tony@thor ~]$ rpm -qR python2-pymod2pkg
/usr/bin/python2
python(abi) = 2.7
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PartialHardlinkSets) <= 4.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
[tony@thor ~]$ grep -s pbr `rpm -ql python2-pymod2pkg`
/usr/lib/python2.7/site-packages/pymod2pkg-0.6.1-py2.7.egg-info/SOURCES.txt:pymod2pkg.egg-info/pbr.json
/usr/lib/python2.7/site-packages/pymod2pkg-0.6.1-py2.7.egg-info/requires.txt:pbr>=1.6
```

Which looks like a bug in the Fedora package :(

**Comment by yac** [comment]
I've added `Required: python-pbr` to the Fedora package for `master`, `f26` and `f25`:

 * [builds](https://koji.fedoraproject.org/koji/packageinfo?packageID=20856)
 * [f26 update](https://bodhi.fedoraproject.org/updates/FEDORA-2017-3edb884d01)
 * [f25 update](https://bodhi.fedoraproject.org/updates/FEDORA-2017-2a29d6ceb0)

**Comment by tbreeds** [comment]
I've left karma on the F26 update.

I'll close this as you've already gone above and beyond, given my poor issue report.

Thanks!
