### ISSUE TITLE
Patch fails with 'int' object has not attribute 'split'

### ISSUE THREAD

**Issue by Akrog** [softwarefactory-project/rdopkg#179]
When we run `rdopkg patch` we get:
```
Traceback (most recent call last):                                                                         
  File "/usr/bin/rdopkg", line 10, in <module>                                                                                             
    sys.exit(main())                                                                                 
  File "/usr/lib/python2.7/site-packages/rdopkg/cli.py", line 49, in main
    sys.exit(rdopkg(*cargs))                             
  File "/usr/lib/python2.7/site-packages/rdopkg/cli.py", line 41, in rdopkg
    version=__version__)                                                                             
  File "/usr/lib/python2.7/site-packages/rdopkg/shell.py", line 87, in run      
    action_runner.engage()                                         
  File "/usr/lib/python2.7/site-packages/rdopkg/core.py", line 212, in engage                                      
    new_args = self.action_manager.run_action(step, self.args)                               
  File "/usr/lib/python2.7/site-packages/rdopkg/action.py", line 252, in run_action                                        
    return action_fun(*fun_args)                                                            
  File "/usr/lib/python2.7/site-packages/rdopkg/actions/distgit/actions.py", line 511, in get_patches_branch
    force)                                                    
  File "/usr/lib/python2.7/site-packages/rdopkg/actionmods/rpmfactory.py", line 35, in fetch_patches_branch
    review_n = _review_number(gerrit_patches_chain)                           
  File "/usr/lib/python2.7/site-packages/rdopkg/actionmods/rpmfactory.py", line 11, in _review_number       
    parts = review_ref.split('/')                                  
AttributeError: 'int' object has no attribute 'split'
```

**Comment by Akrog** [comment]
Proposed fix: https://softwarefactory-project.io/r/16718
