### ISSUE TITLE
get_source_urls fails on Fedora 30

### ISSUE THREAD

**Issue by ktdreyer** [softwarefactory-project/rdopkg#183]
I'm running `rdopkg new-version` on [python-sphinx-removed-in](https://src.fedoraproject.org/rpms/python-sphinx-removed-in) in order to resolve [rhbz#1697060](https://bugzilla.redhat.com/show_bug.cgi?id=1697060)

```
[kdreyer@carbon python-sphinx-removed-in]$ rdopkg new-version
Latest version detected from upstream/master: 0.2.0
Patches branch 'patches/master-patches' not found. Running in --bump-only mode.
Traceback (most recent call last):
  File "/usr/bin/rdopkg", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/rdopkg/cli.py", line 49, in main
    sys.exit(rdopkg(*cargs))
  File "/usr/lib/python3.7/site-packages/rdopkg/cli.py", line 41, in rdopkg
    version=__version__)
  File "/usr/lib/python3.7/site-packages/rdopkg/shell.py", line 87, in run
    action_runner.engage()
  File "/usr/lib/python3.7/site-packages/rdopkg/core.py", line 212, in engage
    new_args = self.action_manager.run_action(step, self.args)
  File "/usr/lib/python3.7/site-packages/rdopkg/action.py", line 252, in run_action
    return action_fun(*fun_args)
  File "/usr/lib/python3.7/site-packages/rdopkg/actions/distgit/actions.py", line 720, in get_source
    source_urls = specfile.Spec().get_source_urls()
  File "/usr/lib/python3.7/site-packages/rdopkg/utils/specfile.py", line 642, in get_source_urls
    if len(sources) == 0:
TypeError: object of type 'filter' has no len()
```

**Comment by ktdreyer** [comment]
I don't see any unit tests for `get_source_urls`. We need to add some before touching this method :(

**Comment by jcapiitao** [comment]
Hi @ktdreyer 
Thank you for opening this issue. I tried to reproduce it in my f30 environment with the last rdopkg release (1.1.1), but it went well.
I think this should have been resolved with this [change](https://github.com/softwarefactory-project/rdopkg/commit/29ebc0613892d46c8dc65c1ce62eceed460c34e3).
Could you give more details about your environment to be able to reproduce the issue please ?

**Comment by apevec** [comment]
worksforme
